# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a870a5a6a8a38e23c765f3bfc6d45b30cb363b23db585c18dbcf2e38098223b0218573f57fbef3d0a74915c2b256c2f20aded02b0e0ce508b10c361d15a83ec8

test:
  secret_key_base: 869c2924f6edbcac346408a27bebb18dee6abd17ee8ed26edac5d57d1b537a07c041d40b7f1aaf6e21074c5386e0d71fd552149fb93f938d533a3a7c6b178977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
